var data=[
"<span class='white'>131****4243</span>	成功转发了<span class='white'>3</span>次，获得<span class='white'>30元</span>红包",
"<span class='white'>158****6798</span>	成功转发了<span class='white'>1</span>次，获得<span class='white'>10元</span>红包",
"<span class='white'>151****5220</span>	成功转发了<span class='white'>1</span>次，获得<span class='white'>10元</span>红包",
"<span class='white'>158****7738</span>	成功转发了<span class='white'>4</span>次，获得<span class='white'>220元</span>红包",
"<span class='white'>130****6102</span>	成功转发了<span class='white'>1</span>次，获得<span class='white'>10元</span>红包",
"<span class='white'>158****1530</span>	成功转发了<span class='white'>7</span>次，获得<span class='white'>70元</span>红包",
"<span class='white'>151****1109</span>	成功转发了<span class='white'>4</span>次，获得<span class='white'>40元</span>红包",
"<span class='white'>158****8611</span>	成功转发了<span class='white'>6</span>次，获得<span class='white'>190元</span>红包",
"<span class='white'>186****1893</span>	成功转发了<span class='white'>7</span>次，获得<span class='white'>70元</span>红包",
"<span class='white'>139****7912</span>	成功转发了<span class='white'>1</span>次，获得<span class='white'>110元</span>红包",
"<span class='white'>139****3064</span>	成功转发了<span class='white'>9</span>次，获得<span class='white'>90元</span>红包",
"<span class='white'>139****1937</span>	成功转发了<span class='white'>7</span>次，获得<span class='white'>70元</span>红包",
"<span class='white'>130****4927</span>	成功转发了<span class='white'>3</span>次，获得<span class='white'>190元</span>红包",
"<span class='white'>158****6945</span>	成功转发了<span class='white'>2</span>次，获得<span class='white'>20元</span>红包",
"<span class='white'>139****7457</span>	成功转发了<span class='white'>8</span>次，获得<span class='white'>80元</span>红包",
"<span class='white'>139****6384</span>	成功转发了<span class='white'>6</span>次，获得<span class='white'>60元</span>红包",
"<span class='white'>158****2635</span>	成功转发了<span class='white'>4</span>次，获得<span class='white'>40元</span>红包",
"<span class='white'>139****7673</span>	成功转发了<span class='white'>1</span>次，获得<span class='white'>10元</span>红包",
"<span class='white'>151****3801</span>	成功转发了<span class='white'>1</span>次，获得<span class='white'>110元</span>红包",
"<span class='white'>139****7979</span>	成功转发了<span class='white'>2</span>次，获得<span class='white'>20元</span>红包",
"<span class='white'>131****2992</span>	成功转发了<span class='white'>4</span>次，获得<span class='white'>40元</span>红包",
"<span class='white'>130****9234</span>	成功转发了<span class='white'>5</span>次，获得<span class='white'>490元</span>红包",
"<span class='white'>158****3223</span>	成功转发了<span class='white'>7</span>次，获得<span class='white'>70元</span>红包",
"<span class='white'>158****6568</span>	成功转发了<span class='white'>7</span>次，获得<span class='white'>70元</span>红包",
"<span class='white'>158****1224</span>	成功转发了<span class='white'>7</span>次，获得<span class='white'>70元</span>红包",
"<span class='white'>151****1470</span>	成功转发了<span class='white'>2</span>次，获得<span class='white'>20元</span>红包",
"<span class='white'>151****1408</span>	成功转发了<span class='white'>8</span>次，获得<span class='white'>80元</span>红包",
"<span class='white'>158****9788</span>	成功转发了<span class='white'>4</span>次，获得<span class='white'>390元</span>红包",
"<span class='white'>158****4588</span>	成功转发了<span class='white'>5</span>次，获得<span class='white'>50元</span>红包",
"<span class='white'>131****1935</span>	成功转发了<span class='white'>1</span>次，获得<span class='white'>10元</span>红包",
"<span class='white'>158****1841</span>	成功转发了<span class='white'>2</span>次，获得<span class='white'>20元</span>红包",
"<span class='white'>155****8557</span>	成功转发了<span class='white'>1</span>次，获得<span class='white'>10元</span>红包",
"<span class='white'>130****8924</span>	成功转发了<span class='white'>5</span>次，获得<span class='white'>50元</span>红包",
"<span class='white'>139****9529</span>	成功转发了<span class='white'>6</span>次，获得<span class='white'>60元</span>红包",
"<span class='white'>158****1657</span>	成功转发了<span class='white'>6</span>次，获得<span class='white'>290元</span>红包",
"<span class='white'>151****7741</span>	成功转发了<span class='white'>9</span>次，获得<span class='white'>90元</span>红包",
"<span class='white'>186****8356</span>	成功转发了<span class='white'>6</span>次，获得<span class='white'>60元</span>红包",
"<span class='white'>158****1261</span>	成功转发了<span class='white'>5</span>次，获得<span class='white'>260元</span>红包",
"<span class='white'>139****8761</span>	成功转发了<span class='white'>2</span>次，获得<span class='white'>20元</span>红包",
"<span class='white'>158****4663</span>	成功转发了<span class='white'>3</span>次，获得<span class='white'>30元</span>红包",
"<span class='white'>139****4442</span>	成功转发了<span class='white'>9</span>次，获得<span class='white'>90元</span>红包",
"<span class='white'>139****1547</span>	成功转发了<span class='white'>8</span>次，获得<span class='white'>470元</span>红包",
"<span class='white'>158****1385</span>	成功转发了<span class='white'>4</span>次，获得<span class='white'>40元</span>红包 ",
"<span class='white'>151****1426</span>	成功转发了<span class='white'>2</span>次，获得<span class='white'>320元</span>红包",
"<span class='white'>139****3301</span>	成功转发了<span class='white'>5</span>次，获得<span class='white'>50元</span>红包",
"<span class='white'>139****3487</span>	成功转发了<span class='white'>7</span>次，获得<span class='white'>70元</span>红包",
"<span class='white'>151****2101</span>	成功转发了<span class='white'>8</span>次，获得<span class='white'>80元</span>红包",
"<span class='white'>155****4552</span>	成功转发了<span class='white'>7</span>次，获得<span class='white'>70元</span>红包",
"<span class='white'>151****8207</span>	成功转发了<span class='white'>8</span>次，获得<span class='white'>480元</span>红包",
"<span class='white'>158****7714</span>	成功转发了<span class='white'>7</span>次，获得<span class='white'>320元</span>红包",
"<span class='white'>158****2832</span>	成功转发了<span class='white'>6</span>次，获得<span class='white'>60元</span>红包",
"<span class='white'>158****3214</span>	成功转发了<span class='white'>9</span>次，获得<span class='white'>90元</span>红包",
"<span class='white'>151****5024</span>	成功转发了<span class='white'>6</span>次，获得<span class='white'>60元</span>红包",
"<span class='white'>158****1729</span>	成功转发了<span class='white'>7</span>次，获得<span class='white'>70元</span>红包",
"<span class='white'>130****8816</span>	成功转发了<span class='white'>3</span>次，获得<span class='white'>30元</span>红包",
"<span class='white'>151****2341</span>	成功转发了<span class='white'>7</span>次，获得<span class='white'>540元</span>红包",
"<span class='white'>158****9920</span>	成功转发了<span class='white'>1</span>次，获得<span class='white'>10元</span>红包",
"<span class='white'>151****5538</span>	成功转发了<span class='white'>7</span>次，获得<span class='white'>70元</span>红包",
"<span class='white'>139****4109</span>	成功转发了<span class='white'>2</span>次，获得<span class='white'>20元</span>红包",
"<span class='white'>158****1282</span>	成功转发了<span class='white'>7</span>次，获得<span class='white'>70元</span>红包",
"<span class='white'>151****3531</span>	成功转发了<span class='white'>5</span>次，获得<span class='white'>50元</span>红包",
"<span class='white'>151****5022</span>	成功转发了<span class='white'>9</span>次，获得<span class='white'>450元</span>红包",
"<span class='white'>151****4736</span>	成功转发了<span class='white'>3</span>次，获得<span class='white'>30元</span>红包",
"<span class='white'>139****3275</span>	成功转发了<span class='white'>5</span>次，获得<span class='white'>50元</span>红包",
"<span class='white'>131****9579</span>	成功转发了<span class='white'>4</span>次，获得<span class='white'>40元</span>红包",
"<span class='white'>155****1471</span>	成功转发了<span class='white'>2</span>次，获得<span class='white'>210元</span>红包",
"<span class='white'>151****4851</span>	成功转发了<span class='white'>8</span>次，获得<span class='white'>80元</span>红包",
"<span class='white'>186****3497</span>	成功转发了<span class='white'>5</span>次，获得<span class='white'>50元</span>红包",
"<span class='white'>139****1657</span>	成功转发了<span class='white'>1</span>次，获得<span class='white'>10元</span>红包",
"<span class='white'>158****5597</span>	成功转发了<span class='white'>6</span>次，获得<span class='white'>60元</span>红包",
"<span class='white'>139****2311</span>	成功转发了<span class='white'>9</span>次，获得<span class='white'>90元</span>红包",
"<span class='white'>158****8351</span>	成功转发了<span class='white'>12</span>次，获得<span class='white'>580元</span>红包",
"<span class='white'>151****4248</span>	成功转发了<span class='white'>5</span>次，获得<span class='white'>50元</span>红包",
"<span class='white'>151****3494</span>	成功转发了<span class='white'>6</span>次，获得<span class='white'>60元</span>红包",
"<span class='white'>136****4475</span>	成功转发了<span class='white'>2</span>次，获得<span class='white'>20元</span>红包",
"<span class='white'>139****7419</span>	成功转发了<span class='white'>8</span>次，获得<span class='white'>390元</span>红包",
"<span class='white'>158****1154</span>	成功转发了<span class='white'>1</span>次，获得<span class='white'>10元</span>红包",
"<span class='white'>139****8909</span>	成功转发了<span class='white'>4</span>次，获得<span class='white'>40元</span>红包",
"<span class='white'>151****7863</span>	成功转发了<span class='white'>9</span>次，获得<span class='white'>90元</span>红包",
"<span class='white'>139****9152</span>	成功转发了<span class='white'>2</span>次，获得<span class='white'>20元</span>红包",
"<span class='white'>180****1878</span>	成功转发了<span class='white'>7</span>次，获得<span class='white'>490元</span>红包",
"<span class='white'>139****5938</span>	成功转发了<span class='white'>2</span>次，获得<span class='white'>20元</span>红包",
"<span class='white'>139****3617</span>	成功转发了<span class='white'>3</span>次，获得<span class='white'>30元</span>红包",
"<span class='white'>151****9868</span>	成功转发了<span class='white'>1</span>次，获得<span class='white'>10元</span>红包",
"<span class='white'>139****7938</span>	成功转发了<span class='white'>2</span>次，获得<span class='white'>20元</span>红包",
"<span class='white'>139****6012</span>	成功转发了<span class='white'>9</span>次，获得<span class='white'>250元</span>红包",
"<span class='white'>151****1661</span>	成功转发了<span class='white'>6</span>次，获得<span class='white'>60元</span>红包",
"<span class='white'>151****4001</span>	成功转发了<span class='white'>7</span>次，获得<span class='white'>70元</span>红包",
"<span class='white'>139****1574</span>	成功转发了<span class='white'>12</span>次，获得<span class='white'>190元</span>红包",
"<span class='white'>151****8515</span>	成功转发了<span class='white'>6</span>次，获得<span class='white'>60元</span>红包",
"<span class='white'>186****7405</span>	成功转发了<span class='white'>6</span>次，获得<span class='white'>60元</span>红包",
"<span class='white'>130****7405</span>	成功转发了<span class='white'>6</span>次，获得<span class='white'>190元</span>红包"
]
console.log(data.length);
var d=1;
function t1(){
	if(d==92){
		d=1;
	}
	for (var i=0;i<data.length;i++ ){
		if(i==d){
			 $(".user p").eq(0).before("<p>"+data[i]+"</p>");
			d++;
			 return true;
		}
	}
}
setInterval(t1,2000);

