
	var countryList={
		 "hot":[
			"United States   美国",
			"South Korea (R.O.K)   韩国",
			"Russia   俄罗斯",
			"Japan   日本",
			"Italy  意大利",
			"India  印度",
			"Germany  德国",
			"France  法国",
			"Canada  加拿大",
			"Australia  澳大利亚"],
		 "A":["Aland Islands (Finland) 奥兰群岛","Albania 阿尔巴尼亚","Algeria 阿尔及利亚","American Samoa 美属萨摩亚","Andorra 安道尔","Angola 安哥拉","Anguilla 安圭拉岛","Antarctica 南极洲","Antigua and Barbuda 安提瓜和巴布达","Argentina 阿根廷","Armenia 亚美尼亚","Armenia 亚美尼亚","Aruba Island 阿鲁巴岛","Ascension Island (U.K.) 阿森松岛","Australia 澳大利亚","Austria 奥地利","Azerbaijan 阿塞拜疆","Azores Islands 亚速尔群岛（葡属）"]  ,
		 "B":["Bahamas 巴哈马","Bahrain 巴林","Bangladesh 孟加拉国","Barbados 巴巴多斯","Belarus 白俄罗斯","Belgium 比利时","Belize 伯利兹","Benin 贝宁","Bermuda Islands 百慕大群岛","Bhutan 不丹","Bolivia 玻利维亚","Bonaire 博内尔","Bosnia and Herzegovina 波斯尼亚和黑塞哥维那","Botswana 博茨瓦纳","Brazil 巴西","British Indian Ocean Territory 英属印度洋领地","Brunei 文莱","Bulgaria 保加利亚","Burkina Faso 布基纳法索","Burundi 布隆迪","Burma 缅甸"]  ,
		 "C":["Cambodia 柬埔寨","Cameroon 喀麦隆","Canada 加拿大","Canary Islands (Spanish) 加那利群岛","Cape Verde 佛得角","Caroline Islands 加罗林群岛","Cayman Islands (U.K.) 开曼群岛","Central African Republic 中非共和国","Chad 乍得","Chagos Archipelago(U.K.) 查戈斯群岛","Chile 智利","China 中国","Christmas Island 圣诞岛","Cocos Islands (Australia) 科科斯群岛","Colombia 哥伦比亚","Comoros 科摩罗","Congo 刚果（金）","Cook Islands 库克群岛","Croatia 克罗地亚","Costa Rica 哥斯达黎加","Cuba  古巴 ","Curacao  库腊索岛 ","Cyprus  塞浦路斯 ","Czech Republic  捷克 "]  ,
		 "D":[
			"Denmark  丹麦 ",
			"Djibouti  吉布提 ",
			"Dominican Republic  多米尼加共和国 ",
			"Dominica  多米尼克 "]  ,
		 "E":[
			"East Timor  东帝汶 ",
			"Eastern Samoa (U.S.)  东萨摩亚 ",
			"Ecuador  厄瓜多尔 ",
			"Egypt  埃及 ",
			"El Salvador  萨尔瓦多 ",
			"Equatorial Guinea  赤道几内亚 ",
			"Eritrea  厄立特里亚 ",
			"Estonia  爱沙尼亚 ",
			"Ethiopia  埃塞俄比亚 "]  ,
		 "F":[
			"Falkland Islands  福克兰岛 ",
			"Faroe Islands  法罗群岛 ",
			"Federated States of Micronesia  密克罗尼西亚 ",
			"Fiji  斐济 ",
			"Finland  芬兰 ",
			"France  法国 ",
			"French Guyana  法属圭亚那 ",
			"France  法国",
			"French Polynesia  法属波利尼西亚 ",
			"French Southern and Antarctic Territories  法属南部及南极领土 "]  ,
		 "G":[
			"Gabon  加蓬 ",
			"Gambia  冈比亚 ",
			"Gambier Islands  盖比群岛 ",
			"Georgia  格鲁吉亚 ",
			"Germany  德国 ",
			"Ghana  加纳 ",
			"Gibraltar (U.K.)  直布罗陀 ",
			"Greenland (Danmark)  格陵兰 ",
			"Grenada  格林纳达 ",
			"Guadeloupe  瓜德罗普 ",
			"Guam  关岛 ",
			"Guatemala  危地马拉 ",
			"Guernsey  格恩西岛 ",
			"Guinea-Bissau  几内亚(比绍) ",
			"Guinea  几内亚 ",
			"Guyana  圭亚那 ",
			"Greece  希腊 "
		]  ,
		 "H":[
			"Haiti  海地 ",
			"Heard Island and McDonald Islands  赫德岛和麦克唐纳群岛 ",
			"Honduras  洪都拉斯 ",
			"Hong Kong  香港 ",
			"Hungary  匈牙利 "
		]  ,
		 "I":[
			"Iceland  冰岛 ",
			"India  印度 ",
			"Indonesia  印度尼西亚 ",
			"Ivory Coast  科特迪瓦 ",
			"Ireland  爱尔兰 ",
			"Isle of Man  马恩岛 ",
			"Israel  以色列 ",
			"Iraq  伊拉克 ",
			"Iran  伊朗 ",
			"Italy  意大利 "
		]  ,
		 "J":[
			"Jamaica  牙买加 ",
			"Japan  日本 ",
			"Jersey  泽西岛 ",
			"Jordan  约旦 ",
		]  ,
		 "K":[
			"Kazakhstan  哈萨克斯坦 ",
			"Kenya  肯尼亚 ",
			"Kerguelen Island (France)  凯尔盖朗岛 ",
			"Kiribati  基里巴斯 ",
			"Kuwait  科威特 ",
			"Kyrgyzstan  吉尔吉斯斯坦 ",
			"Kosovo  科索沃 "
		]  ,
		 "L":[
			"Laos  老挝 ",
			"Latvia  拉脱维亚 ",
			"Lebanon  黎巴嫩 ",
			"Lesotho  莱索托 ",
			"Libya  利比亚 ",
			"Liechtenstein  列支敦士登 ",
			"Lithuania  立陶宛 ",
			"Luxembourg  卢森堡 ",
			"Iran  伊朗 ",
			"Italy  意大利 "
		]  ,
		 "M":[
			"Macao  澳门 ",
			"Macedonia  马其顿 ",
			"Madagascar  马达加斯加 ",
			"Madeira Islands  马德拉群岛 ",
			"Malawi  马拉维 ",
			"Malaysia  马来西亚 ",
			"Maldives  马尔代夫 ",
			"Mali  马里 ",
			"Malta  马耳他 ",
			"Mariana Islands  马里亚纳群岛 ",
			"Marquesas Islands  马克萨斯群岛 ",
			"Marshall Islands  马绍尔群岛 ",
			"Martinique  马提尼克 ",
			"Maslenica  马斯莱尼察 ",
			"Mauritania  毛里塔尼亚 ",
			"Mauritius  毛里求斯 ",
			"Mayotte  马约特 ",
			"Mexico  墨西哥 ",
			"Monaco  摩纳哥 ",
			"Montenegro  黑山共和国 ",
			"Mongolia  蒙古 ",
			"Montserrat  蒙特塞拉特 ",
			"Morocco  摩洛哥 ",
			"Mozambique  莫桑比克 "
		]  ,
		 "N":[
			"Namibia  纳米比亚 ",
			"Nauru  瑙鲁 ",
			"Nepal  尼泊尔 ",
			"Netherlands Antilles  安的列斯（荷属） ",
			"Netherlands  荷兰 ",
			"New Caledonia  新喀里多尼亚 ",
			"New Zealand  新西兰 ",
			"Nicaragua  尼加拉瓜 ",
			"Nigeria  尼日利亚 ",
			"Niger  尼日尔 ",
			"Morocco  摩洛哥 ",
			"Mozambique  莫桑比克 ",
			"Niue  纽埃岛 ",
			"Norfolk Island  诺福克岛 ",
			"Northern Mariana Islands  北马里亚纳群岛 ",
			"Norway  挪威 "
		]  ,
		 "O":[
			"Oman  阿曼 "
		]  ,
		 "P":[
			"Pakistan  巴基斯坦 ",
			"Palau  贝劳共和国 ",
			"Palestine  巴勒斯坦 ",
			"Panama  巴拿马 ",
			"Papua New Guinea  巴布亚新几内亚 ",
			"Paraguay  巴拉圭 ",
			"Peru  秘鲁 ",
			"Philippines  菲律宾 ",
			"Pitcairn  皮特凯恩群岛 ",
			"Poland  波兰 ",
			"Portugal  葡萄牙 ",
			"Principality of Sealand  西兰亲王国 ",
			"Puerto Rico  波多黎各 "
		]  ,
		 "Q":[
			"Qatar  卡塔尔 "
		]  ,
		 "R":[
			"Reunion (France)  留尼汪 ",
			"Russia  俄罗斯 ",
			"Romania  罗马尼亚 "
		]  ,
		 "S":[
			"Saint Barthélemy  圣巴托洛缪 ",
			"Saint GEORGES  圣乔治 ",
			"Saint Helena  圣赫勒拿岛 ",
			"Saint Kitts-Nevis  圣其茨-尼维斯 ",
			"Saint Lucia  圣卢西亚 ",
			"Saint Martin (France)  圣马丁岛 ",
			"Saint Pierre and Miquelon  圣皮埃尔和密克隆岛 ",
			"Saint Vincent and the Grenadines  圣文森特和格林纳丁斯 ",
			"Samoa  萨摩亚 ",
			"San Marino  圣马力诺 ",
			"Sao Tome and Principe  美和普林西比 ",
			"Saudi Arabia  沙特阿拉伯 ",
			"Senegal  塞内加尔 ",
			"Seychelles  塞舌尔 ",
			"Serbia  塞尔维亚 ",
			"Singapore  新加坡 ",
			"Slovakia  斯洛伐克 ",
			"Slovenia  斯洛文尼亚 ",
			"Society Islands  社会群岛 ",
			"Solomon Islands  所罗门群岛 ",
			"Somaliland  索马里兰 ",
			"South Africa  南非 ",
			"South Georgia and the South Sandwich Islands  南乔治亚和南桑德韦奇群岛 ",
			"South Korea (R.O.K)  韩国 ",
			"Spain  西班牙 ",
			"Sri Lanka  斯里兰卡 ",
			"Sudan  苏丹共和国  ",
			"Suriname  苏里南 ",
			"Svalbard and Jan Mayen  斯瓦尔巴特群岛 ",
			"Swaziland  斯威士兰 ",
			"Sweden  瑞典 ",
			"Switzerland  瑞士 "
		]  ,
		 "T":[
			"Taiwan  台湾 ",
			"Tajikistan  塔吉克斯坦 ",
			"Tanzania  坦桑尼亚 ",
			"Thailand  泰国 ",
			"Togo  多哥 ",
			"Tokelau Islands  托克劳群岛 ",
			"Tonga  汤加 ",
			"Trinidad and Tobago  特立尼达和多巴哥 ",
			"Tuamotu Islands  土阿莫土群岛 ",
			"Tubuai Islands  土布艾群岛 ",
			"Tunisia  突尼斯 ",
			"Turkey  土耳其 ",
			"Turkmenistan  土库曼斯坦 ",
			"Turks and Caicos Islands  特克斯和凯科斯群岛 ",
			"Tuvalu  图瓦卢 "
		]  ,
		 "U-Z":[
			"United Arab Emirates  阿拉伯联合酋长国 ",
			"Uganda  乌干达 ",
			"United Kingdom  英国 ",
			"United States Minor Outlying Islands  美国本土外小岛屿 ",
			"United States  美国 ",
			"Ukraine  乌克兰 ",
			"Uruguay  乌拉圭 ",
			"Uzbekistan  乌兹别克斯坦 ",
			"Vanuatu  瓦努阿图 ",
			"Venezuela  委内瑞拉 ",
			"Vietnam  越南 ",
			"Virgin Islands (U.S.)  维尔京群岛（美属） ",
			"Virgin Islands(British)  维尔京群岛（英属） ",
			"Wallis Islands(France)  瓦利斯岛（法） ",
			"Wallis and Futuna  瓦利斯和富图纳群岛 ",
			"Western Africa  西非 ",
			"Western Sahara  西撒哈拉民主共和国 ",
			"Western Samoa  西萨摩亚 ",
			"Yemen  也门 ",
			"Zambia  赞比亚 ",
			"Zimbabwe  津巴布韦 "
		]
	};
	
																								